name: Run Full PSI Scan

on:
  workflow_dispatch:

jobs:
  run-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run PSI scan script
      run: python3 psi-scan.py
      env:
        PSI_API_KEY: ${{ secrets.PSI_API_KEY }}

    - name: Commit all results
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        FILES=$(ls psi_results_*.csv 2>/dev/null || true)
        if [ -n "$FILES" ]; then
          git add $FILES
          git commit -m "Add PSI results batch" || echo "No changes to commit"
          git push
        else
          echo "⚠️ No result CSVs to commit."
