name: Run Full PSI Scan

on:
  workflow_dispatch:

jobs:
  run-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run PSI scan script for urls_part_1
      run: python3 psi-scan.py urls_part_1.txt
      env:
        PSI_API_KEY: ${{ secrets.PSI_API_KEY }}

    - name: Run PSI scan script for urls_part_2
      run: python3 psi-scan.py urls_part_2.txt
      env:
        PSI_API_KEY: ${{ secrets.PSI_API_KEY }}

    - name: Commit all results
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add psi_results_*.csv || echo "No result CSVs to add"
        git commit -m "Add PSI results for all batches" || echo "No changes to commit"
        git push
